name: Check LFS

on:
  push:
  pull_request:

jobs:
  check-lfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: LFS-warning
        uses: ppremk/lfs-warning@v3.3
        with:
            filesizelimit: 10MB